### ISSUE TITLE
请问为什么取消了smb

### ISSUE THREAD

**Issue by Jvaeyhcd** [yellowei/CYPlayer#1]
请问为什么取消了smb，我问下您这个播放器可以播放smb视频吗？

**Comment by yellowei** [comment]
抱歉，未及时回复您。具体原因我也忘了，如果您对FFmpeg需要smb协议的支持，可以搜索我的另一个项目CYFFmpeg。

**Comment by Jvaeyhcd** [comment]
好的，非常感谢！
