### ISSUE TITLE
SMB can be open source？

### ISSUE THREAD

**Issue by azureplus** [yellowei/CYPlayer#4]
SMB can be open source？

**Comment by yellowei** [comment]
支持SMB链接，例如：smb://192.168.1.1/xxx.mp4，也做了smb验证信息的的处理。

**Comment by yellowei** [comment]
> SMB can be open source？

支持SMB链接，例如：smb://192.168.1.1/xxx.mp4，也做了smb验证信息的的处理。

**Comment by yellowei** [comment]
> SMB can be open source？

你需要下载CYFFmpeg用于CYPlayer的cocoapod的本地依赖，CYFFmpeg需要切换到“ALL IN ONE”分支

**Comment by azureplus** [comment]
> > SMB can be open source？
> 
> 你需要下载CYFFmpeg用于CYPlayer的cocoapod的本地依赖，CYFFmpeg需要切换到“ALL IN ONE”分支

build script for CYFFmpeg ?

**Comment by yellowei** [comment]
> > > SMB can be open source？
> > 
> > 
> > 你需要下载CYFFmpeg用于CYPlayer的cocoapod的本地依赖，CYFFmpeg需要切换到“ALL IN ONE”分支
> 
> build script for CYFFmpeg ?
[CYFFmpeg](https://github.com/yellowei/CYFFmpeg), It`s a framework based on ffmpeg, not a script, You can use pod to install it, podfile like this:
`pod 'CYFFmpeg',:path => '../CYFFmpeg'`
