### ISSUE TITLE
pods初始化失败吗？

### ISSUE THREAD

**Issue by SuiFengLiuNian** [yellowei/CYPlayer#5]
pod install   Analyzing dependencies
[!] No podspec found for `CYFFmpeg` in `../CYFFmpeg`

**Comment by yellowei** [comment]
你好， 可以将CYFFmpeg下载下来之后， 通过pod本地安装到工程中。
例如Podfile中这样
```
 pod 'CYFFmpeg',:path => '../../CYFFmpeg'
#  pod 'CYFFmpeg','0.2.2'
  pod 'CYPlayer',:path => '../../CYPlayer'
```
